### ISSUE TITLE
Failed to load remote collections list

### ISSUE THREAD

**Issue by AlexW85** [ksainc/integration_ews#14]
If i want to connect to my local exchange server 2019 i get this with this warning:

<div id="nojavascript">
<div>
Diese Anwendung benötigt JavaScript zum ordnungsgemäßen Betrieb. Bitte <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">aktiviere JavaScript</a> und lade die Seite neu. </div>
</div>

Javascript is installed, nextcloud 27.1.0 is running properly, what can i do?

In the Logs i find this:

[index] Fehler: RuntimeException: Could not resolve host: EWS at <<closure>>

 0. <<closure>>
    OCA\EWS\Components\EWS\EWSClient->__doRequest()
 1. /var/www/nextcloud/apps/integration_ews/lib/Service/Remote/RemoteCommonService.php line 165
    SoapClient->__call()
 2. /var/www/nextcloud/apps/integration_ews/lib/Service/Remote/RemoteContactsService.php line 84
    OCA\EWS\Service\Remote\RemoteCommonService->fetchFoldersByType()
 3. /var/www/nextcloud/apps/integration_ews/lib/Service/CoreService.php line 577
    OCA\EWS\Service\Remote\RemoteContactsService->listCollections()
 4. /var/www/nextcloud/apps/integration_ews/lib/Controller/UserConfigurationController.php line 213
    OCA\EWS\Service\CoreService->fetchRemoteCollections()
 5. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\EWS\Controller\UserConfigurationController->fetchRemoteCollections()
 6. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController()
 7. /var/www/nextcloud/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch()
 8. /var/www/nextcloud/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main()
 9. /var/www/nextcloud/lib/base.php line 1068
    OC\Route\Router->match()
10. /var/www/nextcloud/index.php line 36
    OC::handleRequest()

GET /index.php/apps/integration_ews/fetch-remote-collections

**Comment by AlexW85** [comment]
If i typing the dns name or ip i get „Failed to authenticate with EWS server“

Credentials are right! OWA and EWS is working…

If i type with /ews/exchange.asmx then i get „Failed to load remote collections list“




Mit freundlichen Grüßen


Alexander Weigel
IT-Leiter
stellv. technischer Leiter

Tel: +49 69 90029-297
Mobil: +49 151 27670360
E-mail: ***@***.***<mailto:%7BE-mail%7D>   [https://www.tigerpalast.de/fileadmin/user_upload/Email_Signatur/Logot_p.png]   Tiger & Palmen GmbH & Co. KG
Palmengartenstrasse 11
60325 Frankfurt am Main

Handelsregister Frankfurt am Main
HRB 75 654
www.tiger-palmen.de<http://www.tiger-palmen.de> [https://www.tigerpalast.de/fileadmin/user_upload/Email_Signatur/Xing_32x32.png] <https://www.xing.com/pages/tigerundpalmengmbh-co-kg> [https://www.tigerpalast.de/fileadmin/user_upload/Email_Signatur/Linkedin_32x32.png] <https://www.linkedin.com/company/tiger-palmen-gmbh-co-kg>

[https://www.tigerpalast.de/fileadmin/user_upload/Email_Signatur/Logobanner600px_v2.png]

[https://www.tigerpalast.de/fileadmin/user_upload/Email_Signatur/Email_Banner_Shop.png]<https://shop.tiger-palmen.de/>
Von: Sebastian ***@***.***>
Gesendet: Mittwoch, 20. September 2023 13:51
An: ksainc/integration_ews ***@***.***>
Cc: Alexander Weigel ***@***.***>; Author ***@***.***>
Betreff: Re: [ksainc/integration_ews] Failed to load remote collections list (Issue #14)


Morning,

The Error is "Could not resolve host".

Try typing the host manually.

Sebastian

**Comment by ksainc** [comment]
Hi Alex,

Try the settings like this. And let me know what happens

![image](https://github.com/ksainc/integration_ews/assets/24785599/a1f17ccb-f86c-4114-bb13-7b4b6f266874)

Sebastian

**Comment by AlexW85** [comment]
Failed to authenticate with EWS server!

And in the Logs i see ssl errors then:

SSL: no alternative certificate subject name matches target host name '10.5.0.30'

Nextcloud Notifications over Exchange are working, i'm able to connect over IMAP and SMTP too.


Mit freundlichen Grüßen


Alexander Weigel
IT-Leiter
stellv. technischer Leiter

Tel: +49 69 90029-297
Mobil: +49 151 27670360
E-mail: ***@***.***<mailto:%7BE-mail%7D>   [https://www.tigerpalast.de/fileadmin/user_upload/Email_Signatur/Logot_p.png]   Tiger & Palmen GmbH & Co. KG
Palmengartenstrasse 11
60325 Frankfurt am Main

Handelsregister Frankfurt am Main
HRB 75 654
www.tiger-palmen.de<http://www.tiger-palmen.de> [https://www.tigerpalast.de/fileadmin/user_upload/Email_Signatur/Xing_32x32.png] <https://www.xing.com/pages/tigerundpalmengmbh-co-kg> [https://www.tigerpalast.de/fileadmin/user_upload/Email_Signatur/Linkedin_32x32.png] <https://www.linkedin.com/company/tiger-palmen-gmbh-co-kg>

[https://www.tigerpalast.de/fileadmin/user_upload/Email_Signatur/Logobanner600px_v2.png]

[https://www.tigerpalast.de/fileadmin/user_upload/Email_Signatur/Email_Banner_Shop.png]<https://shop.tiger-palmen.de/>

________________________________
Von: Sebastian ***@***.***>
Gesendet: Mittwoch, 20. September 2023 19:19
An: ksainc/integration_ews
Cc: Alexander Weigel; Author
Betreff: Re: [ksainc/integration_ews] Failed to load remote collections list (Issue #14)


Hi Alex,

Try the settings like this. And let me know what happens

[image]<https://user-images.githubusercontent.com/24785599/269366469-a1f17ccb-f86c-4114-bb13-7b4b6f266874.png>

Sebastian

**Comment by ksainc** [comment]
Ah!

Now we are getting somewhere. I have SSL certificate verification turned on by default. So the domain name in the certificate does not match the host '10.5.0.30'.

A. Is this a self signed certificate?

B. Can you try with your external domain name that the certificate was issued for?

C. Alternatively, You can disable the certificate verification in the code temporarily to test. Change the following line to false. https://github.com/ksainc/integration_ews/blob/2a89655a85afef917c9350f6863b03ecf82aa772/lib/Components/EWS/EWSClient.php#L112

If this works, I can add an option in the code to disable this feature. This was done as a security feature.

**Comment by AlexW85** [comment]
Hi Sebastian,

i began with the external dns name and its a trusted cert from globalsign. With this i get this error:

Exception: OCA\EWS\Service\ConfigurationService::depositAuthenticationBasic(): Argument #3 ($protocol) must be of type string, null given, called in /var/www/nextcloud/apps/integration_ews/lib/Service/CoreService.php on line 319 in file '/var/www/nextcloud/apps/integration_ews/lib/Service/ConfigurationService.php' line 190

FehlerPHP
Undefined array key 0 at /var/www/nextcloud/apps/integration_ews/lib/Service/CoreService.php#307

**Comment by ksainc** [comment]
Hey,

Okay, so according to the last error the the app connected to the exchange server successfully, this time, but could not retrieve the protocol version.

Give me an hour let me test this.

**Comment by ksainc** [comment]
Hey Alex,

I released a new version v1.0.3-beta, update the plugin in Nextcloud and try connecting again.

I changed the protocol discovery so it should not fail with the error you posted.

Try it with you domain first.

But I also added the ability to disable SSL verification, in the EWS Connector admin section.  So if you use your internal address, 10.5.0.30, turn off SSL verification first.

Sebastian

**Comment by AlexW85** [comment]
Hi Sebastian,

thank you for your work and this App. Its the Gamechanger for Nextcloud if it works! But actually there are very much Problems they must be solved.

I can now connect in passive mode with or without ssl and manually set the server address to my external dns name for my exchange server. This only works with unchecked "Configure mail app on successful connection".

A very few calendar entrys are synced, but not all and this entrys are full with the unusable microsoft typical html trash in the describtion.

contacts are not synced at all

tasks and notes seems to work i think, but this is the least important part...

If i delete the connector, all the entrys still persists in the nextcloud. It would be nice if they gone on both sides after delete the connection like activesync on mobiles too. 

The next think is we work very much with deck and my actually favorite wish is to sync deck tasks with exchange calendar, because this 350 calendars and ways to communicate today is horrible. Exchange is the central mail, calendar and contact turntable, but have not very much useful functions. So we need nextcloud... But it must be integrated and harmonize each other. The best think would be to sync the separate calendars to each other, so i have the 2 exchange calendars and the 5 nextcloud calendars (personal, deck 1, deck 2 blabla) in sync together on both systems and can check/uncheck what i want to see. This would allow me to see scheduled deck tasks via activesync on my phone natively.

contacts in exchange over activesync is a bummer. So we need to integrate all nextcloud adressbooks in the one main exchange adressbook, but divide them in nextcloud. This would allow me to create a group adressbook for my team, a global adressbook for my company and share them again with outlook and over activesync with mobiles.

**Comment by ksainc** [comment]
Hey Alex,

Just wanted to let you know, I updated the DB scheme so it will accept item id's of any length. And released the changes.

Try it out and let know.

https://github.com/ksainc/integration_ews/releases/tag/v1.0.5-beta

Sebastian

**Comment by AlexW85** [comment]
Hi Sebastian,

sorry i was very busy yesterday! Thank you for the explanation. All the Microsoft stuff is poor bullshit, it gets more and more like apple, but what will a admin do... Linux KDE is so much better in user experience and stability, but these 3-4 apps they only work with windows are the reason because all the world must use this shit.

I will try the new version now

**Comment by AlexW85** [comment]
Because Deck and the calendar. It would be enough to show only the sheduled Enddate as reminder in calendar.

How can i help you with insomnia?

**Comment by AlexW85** [comment]
i´m on 1.0.6 now and same result as before:

[index] Fehler: Exception: OCP\AppFramework\Db\MultipleObjectsReturnedException: Did not expect more than one result when executing: query "SELECT * FROM `*PREFIX*ews_integration_crls` WHERE (`uid` = :dcValue1) AND (`type` = :dcValue2) AND (`loid` = :dcValue3) AND (`lcid` = :dcValue4)";  in /var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php:292
Stack trace:
#0 /var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php(361): OCP\AppFramework\Db\QBMapper->findOneQuery()
#1 /var/www/nextcloud/apps/integration_ews/lib/Db/CorrelationMapper.php(117): OCP\AppFramework\Db\QBMapper->findEntity()
#2 /var/www/nextcloud/apps/integration_ews/lib/Service/CorrelationsService.php(82): OCA\EWS\Db\CorrelationMapper->findByLocalId()
#3 /var/www/nextcloud/apps/integration_ews/lib/Service/EventsService.php(437): OCA\EWS\Service\CorrelationsService->findByLocalId()
#4 /var/www/nextcloud/apps/integration_ews/lib/Service/EventsService.php(177): OCA\EWS\Service\EventsService->harmonizeLocalAltered()
#5 /var/www/nextcloud/apps/integration_ews/lib/Service/HarmonizationService.php(254): OCA\EWS\Service\EventsService->performHarmonization()
#6 /var/www/nextcloud/apps/integration_ews/lib/Controller/UserConfigurationController.php(171): OCA\EWS\Service\HarmonizationService->performHarmonization()
#7 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(230): OCA\EWS\Controller\UserConfigurationController->Harmonize()
#8 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher->executeController()
#9 /var/www/nextcloud/lib/private/AppFramework/App.php(183): OC\AppFramework\Http\Dispatcher->dispatch()
#10 /var/www/nextcloud/lib/private/Route/Router.php(315): OC\AppFramework\App::main()
#11 /var/www/nextcloud/lib/base.php(1068): OC\Route\Router->match()
#12 /var/www/nextcloud/index.php(36): OC::handleRequest()
#13 {main} at <<closure>>

0. /var/www/nextcloud/apps/integration_ews/lib/Controller/UserConfigurationController.php line 171
   OCA\EWS\Service\HarmonizationService->performHarmonization()
1. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 230
   OCA\EWS\Controller\UserConfigurationController->Harmonize()
2. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 137
   OC\AppFramework\Http\Dispatcher->executeController()
3. /var/www/nextcloud/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch()
4. /var/www/nextcloud/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main()
5. /var/www/nextcloud/lib/base.php line 1068
   OC\Route\Router->match()
6. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

**Comment by AlexW85** [comment]
And this here too:

[PHP] Fehler: Undefined variable $account_name at /var/www/nextcloud/apps/integration_ews/lib/Service/CoreService.php#349

[PHP] Fehler: Undefined array key 0 at /var/www/nextcloud/apps/integration_ews/lib/Service/CoreService.php#333

**Comment by ksainc** [comment]
> i´m on 1.0.6 now and same result as before:
> 
> [index] Fehler: Exception: OCP\AppFramework\Db\MultipleObjectsReturnedException: Did not expect more than one result when executing: query "SELECT * FROM `*PREFIX*ews_integration_crls` WHERE (`uid` = :dcValue1) AND (`type` = :dcValue2) AND (`loid` = :dcValue3) AND (`lcid` = :dcValue4)"; in /var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php:292 Stack trace: #0 /var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php(361): OCP\AppFramework\Db\QBMapper->findOneQuery() #1 /var/www/nextcloud/apps/integration_ews/lib/Db/CorrelationMapper.php(117): OCP\AppFramework\Db\QBMapper->findEntity() #2 /var/www/nextcloud/apps/integration_ews/lib/Service/CorrelationsService.php(82): OCA\EWS\Db\CorrelationMapper->findByLocalId() #3 /var/www/nextcloud/apps/integration_ews/lib/Service/EventsService.php(437): OCA\EWS\Service\CorrelationsService->findByLocalId() #4 /var/www/nextcloud/apps/integration_ews/lib/Service/EventsService.php(177): OCA\EWS\Service\EventsService->harmonizeLocalAltered() #5 /var/www/nextcloud/apps/integration_ews/lib/Service/HarmonizationService.php(254): OCA\EWS\Service\EventsService->performHarmonization() #6 /var/www/nextcloud/apps/integration_ews/lib/Controller/UserConfigurationController.php(171): OCA\EWS\Service\HarmonizationService->performHarmonization() #7 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(230): OCA\EWS\Controller\UserConfigurationController->Harmonize() #8 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher->executeController() #9 /var/www/nextcloud/lib/private/AppFramework/App.php(183): OC\AppFramework\Http\Dispatcher->dispatch() #10 /var/www/nextcloud/lib/private/Route/Router.php(315): OC\AppFramework\App::main() #11 /var/www/nextcloud/lib/base.php(1068): OC\Route\Router->match() #12 /var/www/nextcloud/index.php(36): OC::handleRequest() #13 {main} at <>
> 
>     0. /var/www/nextcloud/apps/integration_ews/lib/Controller/UserConfigurationController.php line 171
>        OCA\EWS\Service\HarmonizationService->performHarmonization()
> 
>     1. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 230
>        OCA\EWS\Controller\UserConfigurationController->Harmonize()
> 
>     2. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 137
>        OC\AppFramework\Http\Dispatcher->executeController()
> 
>     3. /var/www/nextcloud/lib/private/AppFramework/App.php line 183
>        OC\AppFramework\Http\Dispatcher->dispatch()
> 
>     4. /var/www/nextcloud/lib/private/Route/Router.php line 315
>        OC\AppFramework\App::main()
> 
>     5. /var/www/nextcloud/lib/base.php line 1068
>        OC\Route\Router->match()
> 
>     6. /var/www/nextcloud/index.php line 36
>        OC::handleRequest()

So this error means that somehow there where two entries created in the correlation table with the same UUIDs, this was most likely caused, by the crashing due to the key length issue. I need to create a duplicate prevention mechanism, so this does not happen, its on my TODO list.

The easiest way to fix this:

 1. Disconnect the account. This will remove all the correlation entries for this user.
 2. Temporarily create a new test calendar and test address book in NC.
 3. Reconnect the account
 4. Link the Exchange Calendar and Contacts to the Test Calendar and Address Book in NC. (I recommend doing this one at a time. Do the Contacts, then the Calendar.) 

Let me know if that sync's the calendar and contacts properly.

**Comment by ksainc** [comment]
Undefined variable $account_name
You found a bug, I will address this in the next release. Its odd that it did not show up in my testing. But this should not prevent the system from functioning correctly.

Undefined array key 0
This is caused by the exchange protocol version auto discovery. For some reason, your exchange server is not sending back a protocol version correctly or at all. I would need you to run, a command in insomnia to determain the cause of this. I will PM you the instructions.

**Comment by ksainc** [comment]
> Because Deck and the calendar. It would be enough to show only the sheduled Enddate as reminder in calendar.
> 
> How can i help you with insomnia?

I can most likely make this work. Just need to do some investigating on how Deck Works first. Give me a couple weeks on this.

**Comment by ksainc** [comment]
> Hi Sebastian,
> 
> sorry i was very busy yesterday! Thank you for the explanation. All the Microsoft stuff is poor bullshit, it gets more and more like apple, but what will a admin do... Linux KDE is so much better in user experience and stability, but these 3-4 apps they only work with windows are the reason because all the world must use this shit.
> 
> I will try the new version now

No problem! I've been busy myself with my actually job also. Also, I appreciate your patience and testing, as my ability to test this is limited. I can only test with Exchange 365, and GFI's Kerio Connect implementation, you would think that was enough, but it seems On-Premise Exchange, differs in the EWS protocol implementation, auto discovery and SSL.

**Comment by ksainc** [comment]
> Because Deck and the calendar. It would be enough to show only the sheduled Enddate as reminder in calendar.
> 
> How can i help you with insomnia?

Can you email me, at krupinski01@gmail.com. I can send you the Insomnia instructions then, there is no, PM functionality in github.

**Comment by kernsche** [comment]
Hi @ksainc,

thank you for your work on this extension.
I also have the same issues like @AlexW85.
Also in your other project [integration_eas](https://github.com/ksainc/integration_eas)  it seems to be the same issue, because the error messages are pretty much the same.

**Comment by ksainc** [comment]
Hi @kernsche,

The [integration_eas](https://github.com/ksainc/integration_eas) Exchange Active Sync project is NOT ready for testing. 

But I would like to get to the bottom if the issue you are having with this project.

I have been testing this project with O365 and it has been working perfectly for me. So there must be some kind of difference in on-premise servers.  Are you willing to do some testing?

A. At what point are you getting the error?
B. What is the error? And can you share a screenshot.

**Comment by kernsche** [comment]
Hi @ksainc,

I see that the EAS Project ist not ready, but i want to test if the Probleme there will be the same, to help searching the Problem.

A1: I getting the problems after adding the Exchange account without entering the specific exchange server in the personal Settings ->Conneted Accounts tab. Adding the Exchange Server address will resolve the issue.

A2: Also if i check the "Configure mail app on successful connection" setting, therer will be an error

B1: This is the nextcloud.log replacing my credentials, when i let the plugin connect without adding the exchange server adress.

>{"reqId":"dMoFvHRmQOkejyrQW8C5","level":3,"time":"2023-10-01T20:53:29+00:00","remoteAddr":"98.155.97.135","user":"administrator","app":"PHP","method":"GET","url":"/apps/integration_ews/connect-alternate?account_id=USERNAME%40DOMAIN.com&account_secret=PASSWORD&account_server=&flag=false","message":"Undefined array key \"EMailAddress\" at /var/www/html/apps/integration_ews/lib/Service/CoreService.php#208","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.43","version":"27.1.1.0","data":{"app":"PHP"}}

>{"reqId":"KUoSb51cLkKtttIX9Cdu","level":3,"time":"2023-10-01T20:53:30+00:00","remoteAddr":"98.155.97.135","user":"administrator","app":"index","method":"GET","url":"/apps/integration_ews/fetch-remote-collections","message":"Could not resolve host: EWS","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.43","version":"27.1.1.0","exception":{"Exception":"RuntimeException","Message":"Could not resolve host: EWS","Code":6,"Trace":[{"function":"__doRequest","class":"OCA\\EWS\\Components\\EWS\\EWSClient","type":"->"},{"file":"/var/www/html/apps/integration_ews/lib/Service/Remote/RemoteCommonService.php","line":165,"function":"__call","class":"SoapClient","type":"->"},{"file":"/var/www/html/apps/integration_ews/lib/Service/Remote/RemoteContactsService.php","line":84,"function":"fetchFoldersByType","class":"OCA\\EWS\\Service\\Remote\\RemoteCommonService","type":"->"},{"file":"/var/www/html/apps/integration_ews/lib/Service/CoreService.php","line":619,"function":"listCollections","class":"OCA\\EWS\\Service\\Remote\\RemoteContactsService","type":"->"},{"file":"/var/www/html/apps/integration_ews/lib/Controller/UserConfigurationController.php","line":213,"function":"fetchRemoteCollections","class":"OCA\\EWS\\Service\\CoreService","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"fetchRemoteCollections","class":"OCA\\EWS\\Controller\\UserConfigurationController","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1068,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/apps/integration_ews/lib/Components/EWS/EWSClient.php","Line":290,"CustomMessage":"--"}}


B2: This is the nextcloud.log replacing my credentials, when i let the plugin connect with adding the exchange server in the settings manually, but checking the "Configure mail app on successful connection" setting.

> {"reqId":"26c7o0SrLBji8WMKAvm2","level":3,"time":"2023-10-01T21:07:12+00:00","remoteAddr":"98.155.97.135","user":"administrator","app":"PHP","method":"GET","url":"/apps/integration_ews/connect-alternate?account_id=USER%40DOMAIN.com&account_secret=PASSWORD&account_server=EXCHANGESERVERADRESS&flag=true","message":"Undefined` array key \"EMailAddress\" at /var/www/html/apps/integration_ews/lib/Service/CoreService.php#208","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.43","version":"27.1.1.0","data":{"app":"PHP"}}

> {"reqId":"UqNotuPpmZBTTSmFzh0N","level":3,"time":"2023-10-01T21:07:12+00:00","remoteAddr":"98.155.97.135","user":"administrator","app":"index","method":"GET","url":"/apps/integration_ews/fetch-remote-collections","message":"Could not resolve host: EWS","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.43","version":"27.1.1.0","exception":{"Exception":"RuntimeException","Message":"Could not resolve host: EWS","Code":6,"Trace":[{"function":"__doRequest","class":"OCA\\EWS\\Components\\EWS\\EWSClient","type":"->"},{"file":"/var/www/html/apps/integration_ews/lib/Service/Remote/RemoteCommonService.php","line":165,"function":"__call","class":"SoapClient","type":"->"},{"file":"/var/www/html/apps/integration_ews/lib/Service/Remote/RemoteContactsService.php","line":84,"function":"fetchFoldersByType","class":"OCA\\EWS\\Service\\Remote\\RemoteCommonService","type":"->"},{"file":"/var/www/html/apps/integration_ews/lib/Service/CoreService.php","line":619,"function":"listCollections","class":"OCA\\EWS\\Service\\Remote\\RemoteContactsService","type":"->"},{"file":"/var/www/html/apps/integration_ews/lib/Controller/UserConfigurationController.php","line":213,"function":"fetchRemoteCollections","class":"OCA\\EWS\\Service\\CoreService","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"fetchRemoteCollections","class":"OCA\\EWS\\Controller\\UserConfigurationController","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1068,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/apps/integration_ews/lib/Components/EWS/EWSClient.php","Line":290,"CustomMessage":"--"}}

**Comment by ksainc** [comment]
Hi @kernsche

Looks like both B1 and B2 errors are the same "Could not resolve host". 

This means that your NC can't find your Exchange server. So...

A. Are you using the correct domain/ip address?
B. Does NC have the correct routing and permissions to access your Exchange System. (Can you ping from one to the other?)
C. Are the correct ports open on your firewall? (Port 443 HTTPS) 

If the above are good, then try disabling the Secure Transport Verification (SSL Verification), under the Administrator Section -> EWS Connector. This can cause problems, on self-signed SSL certificates, and if the domain dose not match the certificate domain.

**Comment by kernsche** [comment]
Hi @ksainc,

A + B + C: When i put in the exchange server manually by enabling "Configure server manually"  eveything ist working ("Configure mail app on successful connection" is disabled). When i enable "Configure mail app on successful connection" it also wont work also if the server is configured manually.
So i think there is no problem with certificates (which are all corret). It seems that there is a Problem with the autodiscover of the Exchange server.
Also i tested it with disabeling the SSL Verification, which didnt help either.

Also the autodiscover service is working on my clients inside and outside of our network. Also if i run the Microsoft Remote Connectivity test(https://testconnectivity.microsoft.com/tests/Ola/input) on our Exchange Server, everything is working fine according to Microsoft.

**Comment by ksainc** [comment]
Morning,

Okay, maybe there is something wrong with the autodiscovery. Can you send me your autodiscovery file? Type in "https://{your domain}/autodiscover/autodiscover.xml" in to any browser, type in your username and password. That should produce a xml file, make sure you replace {you domain} with your domain.

You can send it to my email, so that it is not posted on here. krupinski01@gmail.com
