### ISSUE TITLE
Nextcloud AiO issue

### ISSUE THREAD

**Issue by GodfatherX64** [ksainc/integration_ews#21]
**Is your feature request related to a problem? Please describe.**

I'm facing this issue when installing inside AiO
is there a fix or just not supported yet?

(App "Exchange EWS Connector (Exchange Web Services)" cannot be installed because the following dependencies are not fulfilled: The library soap is not available)

**Comment by Latschenharry** [comment]
Sadly apt  is not available inside the AiO containers

**Comment by Latschenharry** [comment]
Thank you that worked

**Comment by szaimen** [comment]
Hi, see https://github.com/nextcloud/all-in-one#how-to-add-php-extensions-permanently-to-the-nextcloud-container

**Comment by ksainc** [comment]
Hi @szaimen ,

That would be much easier.

One question tho, will this automatically install the libxml2-dev dependency?

**Comment by szaimen** [comment]
https://github.com/nextcloud/all-in-one/blob/25c5b3dd6579be1cc8f7f3edb274d5ea165767b9/Containers/nextcloud/start.sh#L84

**Comment by ksainc** [comment]
Ah. Its already part of the container creation script! Then yes, That would do it.

Sebastian
