### ISSUE TITLE
"SSL certificate problem: self signed certificate" even if Secure Transport Verification is off

### ISSUE THREAD

**Issue by Mer0me** [ksainc/integration_ews#23]
**Describe the bug**
Account is connected, but no collections are found. Error log says "SSL certificate problem: self signed certificate" even if the switch is off.

**To Reproduce**
1. Connect the account successfully
2. Try to sync

**Expected behavior**
Collections should be displayed

**Screenshots**
![image](https://github.com/ksainc/integration_ews/assets/6248852/a2f3d1e8-8153-46d2-9159-878de30074a7)
Note that there is some hope: it claims it has found some collections in the popup, but they don't display on main windows and don't sync.

![image](https://github.com/ksainc/integration_ews/assets/6248852/040ee014-ec6f-4326-964f-4373768ec316)
Switch is off !

**Desktop (please complete the following information):**

    OS: Debian
    Browser Firefox
    Version 115.4.0esr

**Comment by ksainc** [comment]
Good Morning,

Look like your account is connecting, which is good. And I think you might have found a bug, I might not been setting the SSL setting after the connection process properly. I will look through the code tonight, and issue a fix, if that is a bug.

Sebastian

**Comment by ksainc** [comment]
Yup, I'm a donkey, I was setting the SSL verification to true, even when it should be set to false, if the SSL verification is turned off.

Fixed with Release v1.0.14

Please test the new release and let me know.

Sebastian

**Comment by Mer0me** [comment]
OK, now it connects, I can see the collections, I can associate collections to local calendar, no errors on save an sync, but...
events are not synced...
Neither Exchange to Nextcloud, nor Nextcloud to Exchange.

**Comment by ksainc** [comment]
Morning, Perfect. That means the password issue is fixed. I'm still working on the differences in the Calendar in Exchange 2007.
