### ISSUE TITLE
Getting Enable javascript as an error

### ISSUE THREAD

**Issue by JSChasle** [ksainc/integration_ews#26]
Using Nextcloud Version 27.1.3 and using local Exchange when I enter my credentials I am getting a full page error Failed to authenticate with EWS server: This application need to enable Javascript (and JavaScript is enable and tried different browser) 

Just making sure the FQN am using is mail.fqn.com

When I try using: https://mail.fqn.com/ews/exchange.asmx I am getting Failed to authenticate with EWS server: null

I know it worked before, but disconnected and never was not able to reconnect after

**Comment by ksainc** [comment]
Hi JSChasle,

Yes the FQDN is your domain name "mail.fqn.com". FYI, make sure the SSL certificate matches the domain you are using, otherwise you need to disable "SSL Verification" in the EWS Connector in the Admin section of NC.

The account id is just "user@fqn.com" or "fqn\user" (If you are using windows AD domain)

What version of the App are you using?

What was the last time that it worked?

Sebastian

**Comment by JSChasle** [comment]
Hi,
  Wow thanks for the fast update/awnser back. I am on version 1.0.14 and it work when I tried it about 2 weeks ago. Then tried to configure 1 news user today and got the error message. Went into my account and I was still connected. I did a disconnect and when I tried to do a reconnect (using my account that was working before) I got the error.

**Comment by ksainc** [comment]
Hehehe. You just messaged me at a good time, thats why I answered so quickly. 

That's odd. The only change between .13 and .14 is a fix for a bug that appeared after connection.

Okay, can you send me the error message from the NC log?

**Comment by JSChasle** [comment]
Here it is (I change my username, pass and fqn in the logs)
[index] Erreur: RuntimeException: Autodiscovery failed. at <<closure>>

0. /var/www/html/custom_apps/integration_ews/lib/Service/CoreService.php line 201
   OCA\EWS\Components\EWS\Autodiscover->discover()
1. /var/www/html/custom_apps/integration_ews/lib/Service/CoreService.php line 304
   OCA\EWS\Service\CoreService->locateAccount("jschasle@myfqn.com", "MyP@ssword")
2. /var/www/html/custom_apps/integration_ews/lib/Controller/UserConfigurationController.php line 96
   OCA\EWS\Service\CoreService->connectAccountAlternate("25948FE9-CE3A-4C78-A14A-8FC838623DF7", "jschasle@myfqn.com", "MyP@ssword", "mail.myfqn.com", ["VALIDATE","CONNECT_MAIL"])
3. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 230
   OCA\EWS\Controller\UserConfigurationController->ConnectAlternate("jschasle@myfqn.com", "MyP@ssword", "mail.myfqn.com", "true")
4. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 137
   OC\AppFramework\Http\Dispatcher->executeController(["OCA\\EWS\\Cont ... "], "ConnectAlternate")
5. /var/www/html/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\EWS\\Cont ... "], "ConnectAlternate")
6. /var/www/html/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main("OCA\\EWS\\Contr ... r", "ConnectAlternate", ["OC\\AppFramewo ... "], ["integration_ew ... "])
7. /var/www/html/lib/base.php line 1068
   OC\Route\Router->match("/apps/integration_ews/connect-alternate")
8. /var/www/html/index.php line 36
   OC::handleRequest()

GET /apps/integration_ews/connect-alternate?account_id=jschasle%40myfqn.com&account_secret=MyP@ssword&account_server=mail.myfqn.com&flag=true
from 10.100.16.117 by 25948FE9-CE3A-4C78-A14A-8FC838623DF7 at 2023-11-30T15:18:58+00:00

**Comment by ksainc** [comment]
Morning JSChasle,

So form the error message it looks like you are trying to use the connect mail feature.

This feature relies on information from the AutoDiscovery, and there seems to be something funky with the autodiscovery file.

Can you try without turning on Connect Mail App? If this works we can do some troubleshooting to see, why the autodiscovery is causing issues.

Sebastian

**Comment by JSChasle** [comment]
Thanks found out that soap was removed after an update. So I guess I need to re-add soap (I use Nextcloud AIO so my guess I need to reinstall it after each updates?)

[index] Erreur: Exception: Class "SoapClient" not found in file '/var/www/html/custom_apps/integration_ews/lib/Components/EWS/EWSClient.php' line 36 at <<closure>>

0. /var/www/html/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\EWS\\Cont ... "], "ConnectAlternate")
1. /var/www/html/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main("OCA\\EWS\\Contr ... r", "ConnectAlternate", ["OC\\AppFramewo ... "], ["integration_ew ... "])
2. /var/www/html/lib/base.php line 1068
   OC\Route\Router->match("/apps/integration_ews/connect-alternate")
3. /var/www/html/index.php line 36
   OC::handleRequest()

Caused by:

Error: Class "SoapClient" not found at <<closure>>

0. /var/www/html/lib/composer/composer/ClassLoader.php line 576
   include()
1. /var/www/html/lib/composer/composer/ClassLoader.php line 427
   Composer\Autoload\{closure}("*** sensitive parameters replaced ***")
2. /var/www/html/custom_apps/integration_ews/lib/Service/CoreService.php line 339
   Composer\Autoload\ClassLoader->loadClass("OCA\\EWS\\Components\\EWS\\EWSClient")
3. /var/www/html/custom_apps/integration_ews/lib/Controller/UserConfigurationController.php line 96
   OCA\EWS\Service\CoreService->connectAccountAlternate("25948FE9-CE3A-4C78-A14A-8FC838623DF7", "jschasle@myfqn.com", "MyP@ssword", "mail.myfqn.com", ["VALIDATE"])
4. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 230
   OCA\EWS\Controller\UserConfigurationController->ConnectAlternate("jschasle@myfqn.com", "MyP@ssword", "mail.myfqn.com", "false")
5. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 137
   OC\AppFramework\Http\Dispatcher->executeController(["OCA\\EWS\\Cont ... "], "ConnectAlternate")
6. /var/www/html/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\EWS\\Cont ... "], "ConnectAlternate")
7. /var/www/html/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main("OCA\\EWS\\Contr ... r", "ConnectAlternate", ["OC\\AppFramewo ... "], ["integration_ew ... "])
8. /var/www/html/lib/base.php line 1068
   OC\Route\Router->match("/apps/integration_ews/connect-alternate")
9. /var/www/html/index.php line 36
   OC::handleRequest()

GET /apps/integration_ews/connect-alternate?account_id=jschasle%40myfqn.com&account_secret=MyP@ssword&account_server=mail.myfqn.com&flag=false
from 10.100.16.117 by 25948FE9-CE3A-4C78-A14A-8FC838623DF7 at 2023-11-30T17:20:10+00:00

**Comment by ksainc** [comment]
Hey,

Have a look at issue #21 and at szaimen's comment. There is a link with instruction on how to make it permanent.

Sebastian

**Comment by ksainc** [comment]
Solved
