### ISSUE TITLE
Server gets in a constant Maintenance Loop if Soap is not enable correctlty

### ISSUE THREAD

**Issue by JSChasle** [ksainc/integration_ews#27]
**Describe the bug**
I did not install SOAP correctly and tried to update the EWS package since then my NextCloud is always in maintenance mode (I tried changing the maintenance from true to false and it always come back to true after a restart)

**To Reproduce**
1. Install the EWS Connector
2. It will say the soap package is missing
3. Did this https://github.com/ksainc/integration_ews/issues/21#issuecomment-1820053455
4. Worked until I rebooted the server
5.  I went to the app and updated the EWS Connector to the last version
6. It gave me an error (and then the webpage was unresponsive)
7. Rebooted the server
8. I was given the maintenance page of Nextcloud
9. Change the config.php maintenance mode from true to false
10. Restarted the docker nextcloud-aio-nextcloud
11. Came back to maintenance mode and config.php was changed from false to true
12. Stuck in a loop

**Would need help how to disable the app from command line**
Am using NextCloud AIO  and I can seem to find how to disable the EWS Connector from command line

**Comment by ksainc** [comment]
Hi JSChasle,

To disable the app just run this command from the AIO terminal

sudo -u www-data php --define apc.enable_cli=1 /var/www/nextcloud/occ app:disable integration_eas

But I don't see how the app can cause a maintenance loop. If the php-soap plugin is not installed it will just fail and throw an error.

Sebastian

**Comment by JSChasle** [comment]
Thanks so much. 
Did sudo -u www-data php occ app:list
Found it in the list and then
sudo -u www-data php occ app:disable integration_ews

And sorry for ignorance I can login into the docker as a bash and nano the file but am unable to copy it or how to export it out of the container (I did s screenshot)
![Logs](https://github.com/ksainc/integration_ews/assets/7692731/ca888071-8cd3-4608-9914-0848643d6a85)

**Comment by ksainc** [comment]
Your welcome. Seem the background job is failing every 10min. Which is expected if php soap is missing.

Can you login in now? If yes, can you copy and paste the error from the NC Log screen. Administration -> Logging. The actual error is missing in the picture.

**Comment by JSChasle** [comment]
Hi,

Here it is:

Exception: App "Exchange EWS Connector (Exchange Web Services)" cannot be installed because the following dependencies are not fulfilled: The library soap is not available.

<html>
<body>

Info | updater | \OC\Updater::resetLogLevel: Reset log level to Warning(2) |   | 2023-12-15T00:09:25-0500
-- | -- | -- | -- | --
Info | updater | \OC\Updater::maintenanceActive: Maintenance mode is kept active |   | 2023-12-15T00:09:25-0500
Erreur | updater | \OC\Updater::updateEnd: Update failed |   | 2023-12-15T00:09:25-0500
Erreur | updater | \OC\Updater::failure: Exception: App "Exchange EWS Connector (Exchange Web Services)" cannot be installed because the following dependencies are not fulfilled: The library soap is not available. |   | 2023-12-15T00:09:25-0500
Erreur | no app in context | Exception: App "Exchange EWS Connector (Exchange Web Services)" cannot be installed because the following dependencies are not fulfilled: The library soap is not available. |   | 2023-12-15T00:09:25-0500
Info | updater | \OC\Updater::appUpgradeStarted: Updating <integration_ews> ...


</body>
</html>

/var/www/html/lib/private/legacy/OC_App.php - line 834:

OC_App::checkAppDependencies([ "OC\\AllConfig"], [ "OC\\L10N\\LazyL10N"], [ "*** sensi ... ]], false)

/var/www/html/lib/private/Updater.php - line 359:

OC_App::updateApp("*** sensiti ... *")

/var/www/html/lib/private/Updater.php - line 271:

OC\Updater->doAppUpgrade()

/var/www/html/lib/private/Updater.php - line 139:

OC\Updater->doUpgrade("27.1.4.1", "27.1.4.1")

/var/www/html/core/Command/Upgrade.php - line 225:

OC\Updater->upgrade()

/var/www/html/3rdparty/symfony/console/Command/Command.php - line 298:

OC\Core\Command\Upgrade->execute([ "Symfony\\ ... "], [ "Symfony\\ ... "])

/var/www/html/3rdparty/symfony/console/Application.php - line 1040:

Symfony\Component\Console\Command\Command->run([ "Symfony\\ ... "], [ "Symfony\\ ... "])

/var/www/html/3rdparty/symfony/console/Application.php - line 301:

Symfony\Component\Console\Application->doRunCommand([ "OC\\Core\\Command\\Upgrade"], [ "Symfony\\ ... "], [ "Symfony\\ ... "])

/var/www/html/3rdparty/symfony/console/Application.php - line 171:

Symfony\Component\Console\Application->doRun([ "Symfony\\ ... "], [ "Symfony\\ ... "])

/var/www/html/lib/private/Console/Application.php - line 211:

Symfony\Component\Console\Application->run([ "Symfony\\ ... "], [ "Symfony\\ ... "])

/var/www/html/console.php - line 100:

OC\Console\Application->run()

/var/www/html/occ - line 11:

require_once("/var/www/html/console.php")


Might not be on your side as it seems maintenace is kept when an update (for an app) fails?

**Comment by ksainc** [comment]
Morning,

You are correct. 

Exception: App "Exchange EWS Connector (Exchange Web Services)" cannot be installed because the following dependencies are not fulfilled: The library soap is not available.

Its a logic issue with NC. If one of the app installs fails for any reason, the entire updated process fails. I've found this issue in several places, like the event dispatcher. The event dispatcher process fails completely also if there is an error in any of the event handlers.

If you install the php soap extension again that should fix the install issue.

This time follow szaimen recommendation on how to make the extension permanent.

https://github.com/ksainc/integration_ews/issues/21#issuecomment-1822968254
