### ISSUE TITLE
Calendar are't syncing

### ISSUE THREAD

**Issue by Freshou** [ksainc/integration_ews#30]
i have a long way calendar on exchange and in my NextCloud, and after 24h thins aren't sync between my calendars.... 

As request here:
https://github.com/ksainc/integration_ews/issues/29#issuecomment-1889625674
I open a new ticket for it ! 

Attached my Transport Log
[davidfredette_2024-01-12_12-56-12_EWS.log](https://github.com/ksainc/integration_ews/files/13928835/davidfredette_2024-01-12_12-56-12_EWS.log)

**Comment by ksainc** [comment]
Thank you,

From the transport log it looks like Exchange does not like the app setting the DeletedOccurrence parameter.

**Comment by ksainc** [comment]
Fixed in patch #74acea0

Packaged and released in v1.0.26

**Comment by Freshou** [comment]
i confirme now that all my elements are sync between my O365 calendar and my NextCloud One ! 

Thanx !
