### ISSUE TITLE
Exchange EWS connector app breaks occ command

### ISSUE THREAD

**Issue by nindzaopet** [ksainc/integration_ews#32]
**Describe the bug**
With integration_ews app updated to 1.0.29, I'm unable to execute occ command.
For example, I needed to execute occ db:add-missing-indices and after executing command, I got error shown on the screenshot. 
After disabling EWS connector app and then again execute occ command, everything goes without any error but if I again enable EWS app and try occ command then there is the same error,
I didn't got that kind of error with previous versions and sync worked in both ways.
**Screenshots**

![image](https://github.com/ksainc/integration_ews/assets/156998925/e9b86f1d-8905-4a21-bdf1-f1f69da65d19)

**Additional context**
Also, the EWS app doesn't follow cron.php (every 5 min) update time (currently there is 30 min after I enabled app and synced with Save/Sync but there is no sync after that). I'm not sure if this has any connection with the problem above. 

Nextcloud is at 28.0.1 version. 
PHP version 8.1.2

**Comment by ksainc** [comment]
Morning @nindzaopet 

Looks like in my haste to patch a bug, I included the definition in the AppInfo.xml for a new CLI command I am working on without including the command, I will have a fix for this by tomorrow.

As for your other issue, can you start another ticket, I don't want to pollute the tickets with multiple unrelated issues.

Sebastian

**Comment by satmd** [comment]
For those people currently stuck in *this* situation, there is a a way to get your occ  working again. Only use this workaround until the fixed version of this app has been released!

Edit your `apps/integration_ews/appinfo.xml` to read the `<commands>...</commands>` block like this:
```
<commands>
  <command>OCA\EWS\Commands\Connect</command>
  <command>OCA\EWS\Commands\Disconnect</command>
  <command>OCA\EWS\Commands\Harmonize</command>
</commands>
```

Note the absence of `OCA\EWS\Commands\Correlate`!

**Comment by ksainc** [comment]
Hi @satmd

Thank you for the work around.

**Comment by ksainc** [comment]
The missing command is now included, in release 1.0.30.

**Comment by nindzaopet** [comment]
Thank you for the fast fix. 
I also really appreciate your work with this application.

**Comment by ksainc** [comment]
Morning!

I'm glad the fix worked! and I thank you very much for the kind words!

Sebastian
