### ISSUE TITLE
Error when connecting

### ISSUE THREAD

**Issue by ryshkov46** [ksainc/integration_ews#33]
Good afternoon.
First of all I would like to say thank you for your hard work!
And now to the point:
Nextcloud deployed: **NextCloud 27.1.5**
Deployed Exchange Server: **Version 15.1 (Build 2507.6)**
Installed Exchange EWS Connector: **1.0.30**
When I try to connect to any server (I enter a made up username/password), I see a message about a valid connection, which is strange.
![ews_conn](https://github.com/ksainc/integration_ews/assets/58268655/f96e25a4-377c-4753-a746-db694e3a8985)

If I enter correct login/password/server data from Exchange, I get an error.
![ews_conn_error](https://github.com/ksainc/integration_ews/assets/58268655/9897fe17-bd98-49bb-96fc-8946af02c550)

What settings do I need to make? Should I use NTML authorization or is this an Exchange EWS Connector error?

*P.S. This is my first bug report, if something is wrong I apologize.*

**Comment by ksainc** [comment]
Hi,

This is most likely a SSL verification issue. In the Admin Section -> EWS Connector -> disable Transpost Verification.

Sebastian

**Comment by ryshkov46** [comment]
![image](https://github.com/ksainc/integration_ews/assets/58268655/d00b54d9-a8e4-4773-87b9-50ec8652b3da)
Made your recommendations, the errors are the same and i don't see any errors in nextcloud logs.

**Comment by ksainc** [comment]
Okay, what happens if you connect to your server manually, but DO NOT use configure mail app option?

**Comment by ryshkov46** [comment]
As shown in the first screenshot. I don't get any errors, I only see the connection message and nothing else happens.
![image](https://github.com/ksainc/integration_ews/assets/58268655/fa7a4ea7-d6fc-45f0-90f9-554b5b8abed9)

**Comment by ksainc** [comment]
Okay, so it connects to the exchange server but its not getting a list of collections/folders.

The wired thing is that the app is not even seeing any local collections (NC calendars, contacts, tasks) either, are these apps enabled? and enabled for the account you are connecting?

The app skips retrieval of collections for any app that is disabled, on the system or for that particular user.

**Comment by ryshkov46** [comment]
Im just enabled Apps: Calendar,Contact and error has changed
![image](https://github.com/ksainc/integration_ews/assets/58268655/0245a65a-bb59-47c1-8520-c96ea4b1d109)

The same error occurs if I enter a "made-up" username\ password\ server.

**Comment by ksainc** [comment]
Okay, that image has conflicting information, it say it can't connect but it also shows that it connected.

According to the error, it can't find your server. 

Turn on Transport Log in the Admin section. Then email it to me (do not post it here), as this will have sensitive information. krupinski01@gmail.com

**Comment by ryshkov46** [comment]
What helped:
 - User account in "localdomain\account" format.
 - Once the accounts are connected, the remote folders with calendars and contacts are listed as shown in the figure above. The next step is to create correlations (associations/links/connections) between local and remote collections of calendars and contacts by clicking the link icon next to the remote collection name, selecting the local calendar or contacts address book to associate with it and clicking save(from documentation)
